FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["src/Branef.API/Branef.API.csproj", "Branef.API/"]
RUN dotnet restore "src/Branef.API/Branef.API.csproj"
COPY . .
WORKDIR "/src/Branef.API"
RUN dotnet build "Branef.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Branef.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Branef.API.dll"]
